apiVersion: v1
kind: ServiceAccount
metadata:
  name: lldpad
  namespace: lldpad-ns
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lldpad
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lldpad-cni
subjects:
- kind: ServiceAccount
  name: lldpad
  namespace: lldpad-ns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lldpad-cni
rules:
- apiGroups:
  - lldpad.cni.cncf.io
  resources:
  - ippools
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lldpad
  namespace: lldpad-ns
  labels:
    tier: node
    app: lldpad
spec:
  selector:
    matchLabels:
      name: lldpad
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: lldpad
        name: lldpad
    spec:
      hostNetwork: true      
      serviceAccountName: lldpad
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: lldpad
        image: quay.io/xymox/lldpad-ubi8:latest
        env:
        - name: LLDPAD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cnibin
          mountPath: /host/opt/cni/bin
        - name: cni-net-dir
          mountPath: /host/etc/cni/net.d
      volumes:
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d
