apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# bases:
# - ../../base

namespace: lldpd-test

resources:
- namespace.yaml
- service-account.yaml
- rbac.yaml
###- daemonset-install.yaml
- daemonset-test.yaml
